name: zwave
version: 0.8.0
author: Dan Rubel <danrubel@google.com>
description: >
  A Dart library for interacting with Z-Wave devices
  using the Open Z-Wave library on all major OS platforms.
homepage: https://github.com/danrubel/zwave.dart
environment:
  sdk: '>=1.15.0 <2.0.0'
dependencies:
  args: '>=0.13.7 <1.1.0'
  logging: ^0.11.3
dev_dependencies:
  grinder: ^0.8.0
  mockito: ^2.0.2
  test: ^0.12.4
